---
# The following setup is for the logging system. For information on how to change this
# see https://serilog.net/
Serilog:
  MinimumLevel: 
    Default: Information
  Override: 
    Microsoft: Warning
    System: Warning
  Enrich:
    - FromLogContext
    - WithProcessId
    - WithThreadId
  WriteTo:
    -
      Name: File
      Args:
        path: logs/simpleAirDefense.log
GameServers:
  - 
    # Replace the following example fields with those used by your server and database
    Name: RurouniJones Bestest Server
    # Used in discord commands so keep this unique across your gameservers
    ShortName: RBS
    Rpc:
      Host: rbs.example.com
      # This is the default port
      Port: 50051
  # If you don't need extra servers you can delete this line and everything below it
  -
    Name: RurouniJones Worstest Server
    # Used in discord commands so keep this unique across your gameservers
    ShortName: RWS
    Rpc:
      Host: rws.example.com
      # This is the default port
      Port: 50051